## Server Properties
server:
  port: 8080
  error:
    whitelabel:
      enabled:  false

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring:
  application:
    name: imdb
  jackson:
    time-zone:  UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS:  false

swagger:
  app-info:
    name: IMDB REST API
    description: IMDB project.
    version: V1
    termofserviceurl: /
    license: imdb
    licenseUrl: /
    contact:
      name: imdb
      url: http://www.ibdm.com/
      email: info@ibdb.com

imdb:
  redis:
   host: 127.0.0.1
   port: 6379
